version: "3.5"
services:
  go-course-users:
    platform: linux/amd64
    container_name: go-course-users
    build:
      context: .
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_course_users
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
